name: Create Archive
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    
    - uses: actions/checkout@master
    
    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'ArdFSTCPLibrary.zip'
        exclusions: '*.git* .editorconfig'

    - uses: rickstaa/action-create-tag@v1
      with:
        tag: "latest"
        message: "Latest release"
        force_push_tag: true
        
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "ArdFSTCPLibrary.zip"
        commit: ${{ steps.vars.outputs.sha_short }}
        tag: "latest"
