name: Create Archive
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - uses: rickstaa/action-get-semver@v1
      id: get_semver
      with:
        bump_level: "minor"
      
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'ArdFSTCPLibrary.zip'
        exclusions: '*.git* .editorconfig'

    - uses: rickstaa/action-create-tag@v1
      with:
        tag: ${{ steps.get_semver.outputs.next_version }}
        message: "Latest release"
        force_push_tag: true
        
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "ArdFSTCPLibrary.zip"
        tag: ${{ steps.get_semver.outputs.next_version }}
